version: '3.8'

services:
  # Frontend Servisi (Sitemizin arayüzü)
  frontend:
    build: ./frontend
    ports:
      - "8080:80" # Dışarıdan 8080 portu ile erişeceğiz (http://localhost:8080)
    restart: unless-stopped
    depends_on:
      - backend

  # Backend Servisi (Hatırlatıcı vb. işler)
  backend:
    build: ./backend
    ports:
      - "5001:5000" # Mac'lerde 5000 portu dolu olabildiği için dışarıya 5001 olarak açıyoruz
    env_file:
      - ./backend/.env # Çevresel değişkenleri (.env) içeri aktarıyoruz
    restart: unless-stopped
